version: '3'

services:
  database:
    image: postgres:14.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}" 
      POSTGRES_DB:  "${DB_NAME}"
    